CC  = g++
CXX = g++

CFLAGS   = -g -Wall
CXXFLAGS = -g -Wall -std=c++17 -I ../../

LDLIBS = -lstdc++fs

executable = day11

$(executable):

.PHONY: all clean
all: clean $(executable)
clean:
	rm -f *.o *~ a.out core $(executable) $(executable).exe


